### ISSUE TITLE
Add the ability to look up IP Addresses by address for ip_address_to_interface module 

### ISSUE THREAD

**Issue by edwardtheharris** [edwardtheharris/nautobot-ansible#1]
# ISSUE TYPE

Feature Idea

# SUMMARY

Enable IP Address lookup by address

## Current implementation

```yaml
    - name: "Add IP address on GigabitEthernet4 - test100"
      networktocode.nautobot.ip_address_to_interface:
        url: "{{ nautobot_url }}"
        token: "{{ nautobot_token }}"
        ip_address: "{{ ip_address['key'] }}"
        interface:
          name: GigabitEthernet4
          device: test100
      vars:
        ip_address: "{{ lookup('networktocode.nautobot.lookup', 'ip-addresses', api_endpoint=nautobot_url, token=nautobot_token, api_filter='address=10.100.0.1/32') }}"
```

## Desired implementation

```yaml
    - name: "Add IP address on GigabitEthernet4 - test100"
      networktocode.nautobot.ip_address_to_interface:
        url: "{{ nautobot_url }}"
        token: "{{ nautobot_token }}"
        ip_address:
          address: "10.100.0.1/32"
        interface:
          name: GigabitEthernet4
          device: test100
```

We need to add an iteration to the module utils, but additional changes may be required.
[nautobot-ansible/plugins/module_utils/utils.py](https://github.com/nautobot/nautobot-ansible/blob/7831e3e1dd61c33c316e2173379593a2a870367e/plugins/module_utils/utils.py#L168-L169)

Lines 168 to 169 in [7831e3e](https://github.com/nautobot/nautobot-ansible/commit/7831e3e1dd61c33c316e2173379593a2a870367e)

```json
 "ip_addresses": "ip_addresses", 
 "ipaddresses": "ip_addresses",
```
